name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: nginx

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build --pull --rm -f artifact.Dockerfile -t ear:latest .
